version: 2
jobs:
  docker_push:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run: docker build -t rdhawladar/docker-php-mysql .
      - run: docker push rdhawladar/docker-php-mysql:latest

  deploy:
    machine:
      enable: true
    steps:
      - run: ssh ubuntu@$dev_host "docker run rdhawladar/docker-php-mysql:latest"

workflows:
  version: 2
  build-push:
    jobs:
      - docker_push
      - deploy:
          requires:
            - docker_push
          filters:
            branches:
              only: master
